//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_ASP.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.StagiaireWebServiceSoap")]
    public interface StagiaireWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GestNomsStagiaire", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GestNomsStagiaire(string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GestNomsStagiaire", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GestNomsStagiaireAsync(string date1, string date2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StagiaireWebServiceSoapChannel : ADO_ASP.ServiceReference1.StagiaireWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StagiaireWebServiceSoapClient : System.ServiceModel.ClientBase<ADO_ASP.ServiceReference1.StagiaireWebServiceSoap>, ADO_ASP.ServiceReference1.StagiaireWebServiceSoap {
        
        public StagiaireWebServiceSoapClient() {
        }
        
        public StagiaireWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StagiaireWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StagiaireWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StagiaireWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GestNomsStagiaire(string date1, string date2) {
            return base.Channel.GestNomsStagiaire(date1, date2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GestNomsStagiaireAsync(string date1, string date2) {
            return base.Channel.GestNomsStagiaireAsync(date1, date2);
        }
    }
}
